FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache \
    postgresql-client \
    build-base \
    g++ \
    cairo-dev \
    pango-dev \
    giflib-dev \
    pixman-dev \
    pangomm-dev \
    libjpeg-turbo-dev \
    font-noto \
    freetype-dev

COPY package.json package-lock.json* ./

RUN npm install

COPY . .
COPY entrypoint-dev.sh .
RUN chmod +x ./entrypoint-dev.sh

ENTRYPOINT ["./entrypoint-dev.sh"]
CMD ["npm", "run", "dev"]